name: awesome_period_tracker
description: "An awesome period tracker app, because your cycle deserves a standing ovulation"
publish_to: "none"
version: 1.7.0

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: "3.27.3"

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.3.0
  dio: ^5.7.0
  envied: ^1.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_keyboard_visibility_temp_fork: ^0.1.4
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_secure_storage: ^9.2.4
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  injectable: ^2.5.0
  intl: any
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  skeletonizer: ^1.4.2
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  very_simple_state_manager: ^1.3.0+1

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.3.0
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/svgs/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/google_fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/DMSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFF0F5"
  image: "assets/splash/app_icon.png"
  android_12:
    color: "#FFF0F5"
    image: "assets/splash/app_icon.png"

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/images/ic_android.png"
      adaptive_foreground_image: "assets/images/ic_android.png"
      notification_image: "assets/images/ic_notification.png"
      adaptive_background_color: "#FFF0F5"
    ios:
      enable: true
      image_path: "assets/images/ic_ios.png"
